--[[--------------------------------------------------------------------
    Copyright (C) 2014 Johnny C. Lam.
    See the file LICENSE.txt for copying permission.
--]]--------------------------------------------------------------------

local OVALE, Ovale = ...

local rawset = rawset
local setmetatable = setmetatable
local tostring = tostring

local L = nil
do
	-- Default value is the key itself.
	local MT = {
		__index = function(self, key)
			local value = tostring(key)
			rawset(self, key, value)
			return value
		end,
	}
	L = setmetatable({}, MT)
	Ovale.L = L
end

-- THE REST OF THIS FILE IS AUTOMATICALLY GENERATED.
-- ANY CHANGES MADE BELOW THIS POINT WILL BE LOST.
-- UPDATE TRANSLATIONS AT:
--     http://wow.curseforge.com/addons/ovale/localization

local locale = GetLocale()

if locale == "enUS" then
L["Action bar"] = "Action bar"
L["Affichage numérique"] = "Numeric display"
L["Affiche le temps de recharge sous forme numérique"] = "Show the remaining time in numerical form"
L["Affiche les deux prochains sorts et pas uniquement le suivant"] = "Display two abilities and not only one"
L["Afficher la fenêtre"] = "Show Ovale"
L["Afficher les raccourcis clavier dans le coin inférieur gauche des icônes"] = "Show keyboard shortcuts in the icon bottom-left corner"
L["aoe"] = [=[Attack multiple targets.
Adapts to the total number of enemies.]=]
L["AOE"] = "Multiple-targets rotation"
L["Apparence"] = "Appearance"
L["arcane_mage_burn_phase"] = "Suggest Burn actions"
L["Artifact traits"] = "Artifact traits"
L["Aura lag"] = "Aura lag"
L["Auras (player)"] = "Auras (player)"
L["Auras (target)"] = "Auras (target)"
L["Auras on the player"] = "Auras on the player"
L["Auras on the target"] = "Auras on the target"
L["Blood"] = "Blood"
L["buff"] = "Buffs"
L["Cacher bouton vide"] = "Hide empty buttons"
L["Cacher dans les véhicules"] = "Hide in vehicles"
L["Cacher la fenêtre"] = "Hide Ovale"
L["Cacher si cible amicale ou morte"] = "Hide if friendly or dead target"
L["Caractère de portée"] = "Range indicator"
L["cd"] = [=[Long cooldown abilities.
Cast as soon as possible or for increased-damage phases.]=]
L["Ce caractère est affiché dans un coin de l'icône pour indiquer si la cible est à portée"] = "This text is displayed on the icon to show if the target is in range"
L["Click to select the script."] = "Click to select the script."
L["Cliquer pour afficher/cacher les options"] = "Click to hide/show options"
L["Code"] = "Code"
L["Colors"] = "Colors"
L["Copier sur Script personnalisé"] = "Copy to custom script"
L["Correction de la latence"] = "Latency correction"
L["Debug"] = "Debug"
L["Debug aura"] = "Track aura management."
L["Debug compile"] = "Track when the script is compiled."
L["Debug enemies"] = "Track enemy detection."
L["Debug GUID"] = "Track changes to the UnitID/GUID pairings."
L["Debug missing spells"] = "Warn if a known spell ID is used that is missing from the spellbook."
L["Debug unknown spells"] = "Warn if an unknown spell ID is used in the script."
L["Décalage horizontal des options"] = "Options horizontal shift"
L["Décalage vertical des options"] = "Options vertical shift"
L["Défilement"] = "Scrolling"
L["Disabled"] = "Disabled"
L["Display refresh statistics"] = "Display refresh statistics"
L["Ecraser le Script personnalisé préexistant?"] = "Overwrite existing custom script?"
L["En combat uniquement"] = "Show in combat only"
L["Enable debugging messages for the %s module."] = "Enable debugging messages for the %s module."
L["Enable profiling for the %s module."] = "Enable profiling for the %s module."
L["Enabled"] = "Enabled"
L["Flash brightness"] = "Flash brightness"
L["Flash size"] = "Flash size"
L["Flash spells"] = "Flash spells"
L["Flash spells on action bars when they are ready to be cast. Requires SpellFlashCore"] = "Flash spells on action bars when they are ready to be cast. Requires SpellFlashCore"
L["Flash threshold"] = "Flash threshold"
L["Focus"] = "Focus"
L["Groupe d'icônes"] = "Icon group"
L["Horizontal offset"] = "Horizontal offset"
L["Horizontal offset from the center of the screen."] = "Horizontal offset from the center of the screen."
L["Icône"] = "Icon"
L["Ignorer les clics souris"] = "Ignore mouse clicks"
L["Illuminer l'icône"] = "Highlight icon"
L["Illuminer l'icône quand la technique doit être spammée"] = "Hightlight icon when ability should be spammed"
L["Illuminer l'icône quand le temps de recharge est écoulé"] = "Flash the icon when the ability is ready"
L["Input"] = "Input"
L["interrupt"] = "Interrupts"
L["Interrupts"] = "Interrupts"
L["Inverser la boîte à cocher "] = "Toggle check box"
L["La taille des icônes"] = "The icons scale"
L["La taille des petites icônes"] = "The small icons scale"
L["La taille des polices"] = "The font scale"
L["Lag (in milliseconds) between when an spell is cast and when the affected aura is applied or removed"] = "Lag (in milliseconds) between when an spell is cast and when the affected aura is applied or removed"
L["Layout"] = "Layout"
L["Les icônes se déplacent"] = "Scroll the icons"
L["Long cooldown abilities"] = "Long cooldown abilities"
L["main"] = "Main attack"
L["Main attack"] = "Main attack"
L["mana"] = "Mana gain"
L["Marge entre deux icônes"] = "Margin between icons"
L["Middle-Click to toggle the script options panel."] = "Middle-Click to toggle the script options panel."
L["Modules"] = "Modules"
L["moving"] = "Attacks to use while moving"
L["multidot"] = "Damage-over-time on multiple targets"
L["None"] = "None"
L["not_in_melee_range"] = "Not in melee range"
L["offgcd"] = [=[Out of global cooldown ability.
Cast alongside your main attack.]=]
L["Only count a mob as an enemy if it is directly affected by a player's spells."] = "Only count a mob as an enemy if it is directly affected by a player's spells."
L["Only count tagged enemies"] = "Only count tagged enemies"
L["Opacité des icônes"] = "Icons opacity"
L["Opacité des options"] = "Options opacity"
L["Open configuration panel in a separate, movable window."] = "Open configuration panel in a separate, movable window."
L["Options"] = "Options"
L["Output"] = "Output"
L["Overrides"] = "Overrides"
L["Ping for Ovale users in group"] = "Ping for Ovale users in group"
L["Power"] = "Power"
L["predict"] = "Next non-filler attack."
L["Prédictif"] = "Two abilities"
L["Profiling"] = "Profiling"
L["Raccourcis clavier"] = "Keyboard shortcuts"
L["Reset"] = "Reset"
L["Reset the profiling statistics."] = "Reset the profiling statistics."
L["Right-Click for options."] = "Right-Click for options."
L["Script"] = "Script"
L["Script défaut"] = "Default script"
L["Script personnalisé"] = "Custom script"
L["Shift-Right-Click for the current trace log."] = "Shift-Right-Click for the current trace log."
L["Short cooldown abilities"] = "Short cooldown abilities"
L["shortcd"] = [=[Short cooldown abilities.
Cast as soon as possible.]=]
L["Show"] = "Show"
L["Show hidden"] = "Show hidden"
L["Show minimap icon"] = "Show minimap icon"
L["Show the profiling statistics."] = "Show the profiling statistics."
L["Show Trace Log"] = "Show Trace Log"
L["Show version number"] = "Show version number"
L["showwait"] = "Show the wait icon"
L["Si cible uniquement"] = "If has target"
L["SimulationCraft Profile"] = "SimulationCraft Profile"
L["SIMULATIONCRAFT_OVERRIDES_DESCRIPTION"] = "Script code inserted immediately after Include() script statements to override standard definitions, e.g., |cFFFFFF00SpellInfo(tigers_fury tag=main)|r"
L["Spellbook"] = "Spellbook"
L["Stances"] = "Stances"
L["Standalone options"] = "Standalone options"
L["summon_pet"] = "Summon pet."
L["Taille des icônes"] = "Icon scale"
L["Taille des petites icônes"] = "Small icon scale"
L["Taille des polices"] = "Font scale"
L["Taille du second icône"] = "Second icon size"
L["Talents"] = "Talents"
L["The contents of a SimulationCraft profile."] = "The contents of a SimulationCraft profile."
L["The script translated from the SimulationCraft profile."] = "The script translated from the SimulationCraft profile."
L["Time (in milliseconds) to begin flashing the spell to use before it is ready."] = "Time (in milliseconds) to begin flashing the spell to use before it is ready."
L["Top 3"] = "Top 3"
L["Trace"] = "Trace"
L["Trace Log"] = "Trace Log"
L["Trace the next frame update."] = "Trace the next frame update."
L["Verrouiller position"] = "Lock position"
L["Vertical"] = "Vertical"
L["Vertical offset"] = "Vertical offset"
L["Vertical offset from the center of the screen."] = "Vertical offset from the center of the screen."
L["Visibilité"] = "Visibility"

elseif locale == "zhCN" then
--Translation missing 
-- L["Action bar"] = ""
L["Affichage numérique"] = "数字显示"
L["Affiche le temps de recharge sous forme numérique"] = "用数字显示剩余时间"
L["Affiche les deux prochains sorts et pas uniquement le suivant"] = "显示下2个需要释放的技能而不仅是1个"
L["Afficher la fenêtre"] = "显示Ovale"
L["Afficher les raccourcis clavier dans le coin inférieur gauche des icônes"] = "在图标左下角显示快捷键"
L["aoe"] = "多目标攻击"
L["AOE"] = "AOE输出循环"
L["Apparence"] = "环境"
--Translation missing 
-- L["arcane_mage_burn_phase"] = ""
--Translation missing 
-- L["Artifact traits"] = ""
L["Aura lag"] = "触发与移除效果延迟"
--Translation missing 
-- L["Auras (player)"] = ""
--Translation missing 
-- L["Auras (target)"] = ""
--Translation missing 
-- L["Auras on the player"] = ""
--Translation missing 
-- L["Auras on the target"] = ""
L["Blood"] = "鲜血"
L["buff"] = "增益"
L["Cacher bouton vide"] = "隐藏空按钮的背景"
L["Cacher dans les véhicules"] = "使用载具时隐藏"
L["Cacher la fenêtre"] = "隐藏Ovale"
L["Cacher si cible amicale ou morte"] = "当目标是友方或已死亡时隐藏"
L["Caractère de portée"] = "距离显示"
L["cd"] = [=[长CD的爆发技能与物品。
卡CD使用或在boss增伤阶段使用。]=]
L["Ce caractère est affiché dans un coin de l'icône pour indiquer si la cible est à portée"] = "显示在技能图标上的符号以检测与目标的距离"
L["Click to select the script."] = "点击以选取脚本"
L["Cliquer pour afficher/cacher les options"] = "点击来隐藏/显示选项"
L["Code"] = "代码"
--Translation missing 
-- L["Colors"] = ""
L["Copier sur Script personnalisé"] = "复制到自定义脚本"
L["Correction de la latence"] = "延迟修正"
--Translation missing 
-- L["Debug"] = ""
L["Debug aura"] = "追踪光环管理."
L["Debug compile"] = "追踪已编译脚本."
L["Debug enemies"] = "追踪敌人侦测."
L["Debug GUID"] = "追踪UnitID/GUID配对变化."
L["Debug missing spells"] = "使用的已知法术ID在法术书中无法找到时提醒."
L["Debug unknown spells"] = "脚本中使用了未知的法术ID时提醒."
L["Décalage horizontal des options"] = "选项水平移位"
L["Décalage vertical des options"] = "选项垂直移位"
L["Défilement"] = "滑动动画显示下一个技能"
--Translation missing 
-- L["Disabled"] = ""
--Translation missing 
-- L["Display refresh statistics"] = ""
L["Ecraser le Script personnalisé préexistant?"] = "覆盖已存在的自定义脚本?"
L["En combat uniquement"] = "仅在战斗中显示"
--Translation missing 
-- L["Enable debugging messages for the %s module."] = ""
--Translation missing 
-- L["Enable profiling for the %s module."] = ""
--Translation missing 
-- L["Enabled"] = ""
L["Flash brightness"] = "闪光亮度"
L["Flash size"] = "闪光尺寸"
L["Flash spells"] = "法术闪光"
L["Flash spells on action bars when they are ready to be cast. Requires SpellFlashCore"] = "当技能冷却结束时显示闪光效果。需要插件SpellFLashCore"
L["Flash threshold"] = "闪光阈值"
L["Focus"] = "焦点"
L["Groupe d'icônes"] = "图标分组"
--Translation missing 
-- L["Horizontal offset"] = ""
--Translation missing 
-- L["Horizontal offset from the center of the screen."] = ""
L["Icône"] = "图标"
L["Ignorer les clics souris"] = "忽略鼠标点击"
L["Illuminer l'icône"] = "高亮显示图标"
L["Illuminer l'icône quand la technique doit être spammée"] = "当技能应重复使用时高亮显示图标"
L["Illuminer l'icône quand le temps de recharge est écoulé"] = "技能就绪时闪烁图标"
--Translation missing 
-- L["Input"] = ""
L["interrupt"] = "打断施法"
L["Interrupts"] = "打断施法"
L["Inverser la boîte à cocher "] = "开启/关闭选择框"
L["La taille des icônes"] = "图标大小"
L["La taille des petites icônes"] = "小型图标大小"
L["La taille des polices"] = "字体大小"
L["Lag (in milliseconds) between when an spell is cast and when the affected aura is applied or removed"] = "释放一个技能与其触发/移除效果之间的延迟"
--Translation missing 
-- L["Layout"] = ""
L["Les icônes se déplacent"] = "滚动图标"
L["Long cooldown abilities"] = "长CD的技能与物品"
L["main"] = "主要攻击技能"
L["Main attack"] = "主要攻击技能"
L["mana"] = "法力获取"
L["Marge entre deux icônes"] = "图标间距"
--Translation missing 
-- L["Middle-Click to toggle the script options panel."] = ""
--Translation missing 
-- L["Modules"] = ""
L["moving"] = "移动中使用攻击"
L["multidot"] = "多目标持续伤害"
L["None"] = "无"
L["not_in_melee_range"] = "脱离近战范围"
L["offgcd"] = [=[无公共冷却的技能与物品
可以在你使用主攻技能的同时使用。]=]
--Translation missing 
-- L["Only count a mob as an enemy if it is directly affected by a player's spells."] = ""
--Translation missing 
-- L["Only count tagged enemies"] = ""
L["Opacité des icônes"] = "图标透明度"
L["Opacité des options"] = "选项透明度"
--Translation missing 
-- L["Open configuration panel in a separate, movable window."] = ""
L["Options"] = "选项"
--Translation missing 
-- L["Output"] = ""
--Translation missing 
-- L["Overrides"] = ""
--Translation missing 
-- L["Ping for Ovale users in group"] = ""
--Translation missing 
-- L["Power"] = ""
L["predict"] = "下一个非填充性技能。"
L["Prédictif"] = "两个技能"
--Translation missing 
-- L["Profiling"] = ""
L["Raccourcis clavier"] = "快捷键"
--Translation missing 
-- L["Reset"] = ""
--Translation missing 
-- L["Reset the profiling statistics."] = ""
L["Right-Click for options."] = "右键点击打开选项"
L["Script"] = "脚本"
L["Script défaut"] = "默认脚本"
L["Script personnalisé"] = "自定义脚本"
--Translation missing 
-- L["Shift-Right-Click for the current trace log."] = ""
L["Short cooldown abilities"] = "短CD技能"
L["shortcd"] = [=[短CD技能.
卡CD使用]=]
--Translation missing 
-- L["Show"] = ""
L["Show hidden"] = "显示隐藏的脚本"
L["Show minimap icon"] = "在小地图上显示图标"
--Translation missing 
-- L["Show the profiling statistics."] = ""
--Translation missing 
-- L["Show Trace Log"] = ""
--Translation missing 
-- L["Show version number"] = ""
L["showwait"] = "显示等待图标"
L["Si cible uniquement"] = "当目标存在时"
--Translation missing 
-- L["SimulationCraft Profile"] = ""
--Translation missing 
-- L["SIMULATIONCRAFT_OVERRIDES_DESCRIPTION"] = ""
--Translation missing 
-- L["Spellbook"] = ""
--Translation missing 
-- L["Stances"] = ""
--Translation missing 
-- L["Standalone options"] = ""
L["summon_pet"] = "召唤宠物。"
L["Taille des icônes"] = "图标大小"
L["Taille des petites icônes"] = "小型图标大小"
L["Taille des polices"] = "字体大小"
L["Taille du second icône"] = "第二图标大小"
--Translation missing 
-- L["Talents"] = ""
--Translation missing 
-- L["The contents of a SimulationCraft profile."] = ""
--Translation missing 
-- L["The script translated from the SimulationCraft profile."] = ""
L["Time (in milliseconds) to begin flashing the spell to use before it is ready."] = "在技能冷却时间结束之前开始闪光的提前量（毫秒）"
--Translation missing 
-- L["Top 3"] = ""
--Translation missing 
-- L["Trace"] = ""
--Translation missing 
-- L["Trace Log"] = ""
--Translation missing 
-- L["Trace the next frame update."] = ""
L["Verrouiller position"] = "锁定位置"
L["Vertical"] = "垂直"
--Translation missing 
-- L["Vertical offset"] = ""
--Translation missing 
-- L["Vertical offset from the center of the screen."] = ""
L["Visibilité"] = "可见设置"

elseif locale == "zhTW" then
L["Action bar"] = "快捷列"
L["Affichage numérique"] = "顯示數字"
L["Affiche le temps de recharge sous forme numérique"] = "技能剩餘時間以數字顯示"
L["Affiche les deux prochains sorts et pas uniquement le suivant"] = "顯示兩組技能圖示"
L["Afficher la fenêtre"] = "顯示輸出助手"
L["Afficher les raccourcis clavier dans le coin inférieur gauche des icônes"] = "顯示快捷列左下角的超出距離提醒圖示"
L["aoe"] = [=[AOE 範圍攻擊
根據敵人的總數來選擇。]=]
L["AOE"] = "AOE 範圍攻擊"
L["Apparence"] = "外觀"
L["arcane_mage_burn_phase"] = "奧法暴衝階段"
L["Artifact traits"] = "神兵武器特長"
L["Aura lag"] = "增益/減益效果延遲"
L["Auras (player)"] = "光環 (玩家)"
L["Auras (target)"] = "光環 (目標)"
L["Auras on the player"] = "玩家身上的光環"
L["Auras on the target"] = "目標身上的光環"
L["Blood"] = "血量"
L["buff"] = "提示能施放的增益法術"
L["Cacher bouton vide"] = "隱藏空的按鈕"
L["Cacher dans les véhicules"] = "使用載具時隱藏"
L["Cacher la fenêtre"] = "隱藏輸出助手"
L["Cacher si cible amicale ou morte"] = "隱藏友好或已死亡的目標"
L["Caractère de portée"] = "範圍提醒"
L["cd"] = [=[冷卻時間長的技能 (大招)
盡快施放，或在爆發期使用。]=]
L["Ce caractère est affiché dans un coin de l'icône pour indiquer si la cible est à portée"] = "自訂一段文字，如果目標是在範圍內，這段文字會在圖示上顯示提醒你。"
L["Click to select the script."] = "左鍵選擇腳本。"
L["Cliquer pour afficher/cacher les options"] = "左鍵點擊 隱藏/顯示選項"
L["Code"] = "程式碼"
L["Colors"] = "顏色"
L["Copier sur Script personnalisé"] = "複製到自訂腳本"
L["Correction de la latence"] = "延遲校正"
L["Debug"] = "除錯"
L["Debug aura"] = "追蹤光環管理。"
L["Debug compile"] = "追蹤已編譯腳本。"
L["Debug enemies"] = "追蹤敵人偵測。"
L["Debug GUID"] = "追蹤UnitID/GUID配對變化。"
L["Debug missing spells"] = "使用的已知法術ID在法術書中無法找到時提醒。"
L["Debug unknown spells"] = "腳本中使用了未知法術ID時提醒。"
L["Décalage horizontal des options"] = "水平移動框架"
L["Décalage vertical des options"] = "垂直移動框架"
L["Défilement"] = "滾動圖示"
L["Disabled"] = "停用"
L["Display refresh statistics"] = "顯示刷新統計"
L["Ecraser le Script personnalisé préexistant?"] = "是否要覆寫已有的自訂腳本?"
L["En combat uniquement"] = "只在戰鬥中顯示"
L["Enable debugging messages for the %s module."] = "啟用 %s 模組的除錯訊息。"
L["Enable profiling for the %s module."] = "啟用 %s 模組的描述檔。"
L["Enabled"] = "啟用"
L["Flash brightness"] = "閃爍亮度"
L["Flash size"] = "閃爍尺寸"
L["Flash spells"] = "法術閃爍"
L["Flash spells on action bars when they are ready to be cast. Requires SpellFlashCore."] = "法術技能可以施放時，閃爍快捷列中的圖示。需要 SpellFlashCore 插件。"
L["Flash threshold"] = "閃爍條件"
L["Focus"] = "專注目標"
L["Groupe d'icônes"] = "圖示群組"
L["Horizontal offset"] = "水平位置"
L["Horizontal offset from the center of the screen."] = "距離畫面正中央的水平方向移動距離。"
L["Icône"] = "圖示"
L["Ignorer les clics souris"] = "忽略滑鼠點擊"
L["Illuminer l'icône"] = "顯著標示圖示"
L["Illuminer l'icône quand la technique doit être spammée"] = "技能應該大量使用時顯著標示技能圖示"
L["Illuminer l'icône quand le temps de recharge est écoulé"] = "技能可用時閃爍圖示"
L["Input"] = "輸入"
L["interrupt"] = "斷法技能"
L["Interrupts"] = "斷法技能"
L["Inverser la boîte à cocher "] = "勾選或取消核取方塊"
L["La taille des icônes"] = "調整圖示大小"
L["La taille des petites icônes"] = "調整小圖示大小"
L["La taille des polices"] = "調整字體大小"
L["Lag (in milliseconds) between when an spell is cast and when the affected aura is applied or removed"] = "法術施放後和受到光環影響之間的延遲時間 (毫秒)"
L["Layout"] = "版面配置"
L["Les icônes se déplacent"] = "圖示以滾動方式顯示"
L["Long cooldown abilities"] = "冷卻時間長的大招"
L["main"] = "主要攻擊"
L["Main attack"] = "主要攻擊"
L["mana"] = "獲得法力"
L["Marge entre deux icônes"] = "圖示間距"
L["Middle-Click to toggle the script options panel."] = "中鍵切換腳本選項面板。"
L["Modules"] = "模組"
L["moving"] = "移動時可使用的攻擊技能"
L["multidot"] = "對多個目標的持續性傷害 DOT"
L["None"] = "無"
L["not_in_melee_range"] = "超出近戰範圍指示"
L["offgcd"] = [=[不受共用冷卻時間影響的技能
和主要攻擊技能一起施放。]=]
L["Only count a mob as an enemy if it is directly affected by a player's spells."] = "計算直接受到玩家法術影響的敵人。"
L["Only count tagged enemies"] = "只有直接受影響的敵人"
L["Opacité des icônes"] = "圖示透明度"
L["Opacité des options"] = "選項透明度"
L["Open configuration panel in a separate, movable window."] = "選項設定面板開啟為可以移動的獨立視窗。"
L["Options"] = "選項"
L["Output"] = "輸出"
L["Overrides"] = "覆寫"
L["Ping for Ovale users in group"] = "隊伍中其他玩家的輸出助手版本"
L["Power"] = "能量"
L["predict"] = "下一個非填補攻擊。"
L["Prédictif"] = "預測"
L["Profiling"] = "描述檔"
L["Raccourcis clavier"] = "顯示快捷鍵"
L["Reset"] = "重置"
L["Reset the profiling statistics."] = "重置描述檔統計。"
L["Right-Click for options."] = "右鍵開啟選項。"
L["Script"] = "腳本"
L["Script défaut"] = "預設腳本"
L["Script personnalisé"] = "自訂腳本"
L["Shift-Right-Click for the current trace log."] = "Shift+右鍵顯示目前追蹤記錄。"
L["Short cooldown abilities"] = "冷卻時間短的技能"
L["shortcd"] = [=[冷卻時間短的技能
儘快施放，或卡GCD、無招可放時使用。]=]
L["Show"] = "顯示"
L["Show hidden"] = "顯示隱藏的腳本"
L["Show minimap icon"] = "顯示小地圖按鈕"
L["Show the profiling statistics."] = "顯示描述檔統計。"
L["Show Trace Log"] = "顯示追蹤記錄"
L["Show version number"] = "顯示版本編號"
L["showwait"] = "顯示等待圖示"
L["Si cible uniquement"] = "有目標才顯示"
L["SimulationCraft Profile"] = "SimulationCraft 設定檔"
L["SIMULATIONCRAFT_OVERRIDES_DESCRIPTION"] = "緊接在 Include() 之後的程式碼會覆寫標準定義，例如 |cFFFFFF00SpellInfo(tigers_fury tag=main)|r"
L["Spellbook"] = "法術書"
L["Stances"] = "姿勢形態"
L["Standalone options"] = "獨立設定視窗"
L["summon_pet"] = "召喚寵物。"
L["Taille des icônes"] = "圖示大小"
L["Taille des petites icônes"] = "小圖示大小"
L["Taille des polices"] = "字體大小"
L["Taille du second icône"] = "第二圖示大小"
L["Talents"] = "天賦"
L["The contents of a SimulationCraft profile."] = "SimulationCraft 設定檔內容。"
L["The script translated from the SimulationCraft profile."] = "依據 SimulationCraft 設定檔轉譯的腳本。"
L["Time (in milliseconds) to begin flashing the spell to use before it is ready."] = "法術能夠使用前，多久開始閃爍 (毫秒)"
L["Top 3"] = "Top 3"
L["Trace"] = "追蹤"
L["Trace Log"] = "追蹤記錄"
L["Trace the next frame update."] = "追蹤下一個畫面更新。"
L["Verrouiller position"] = "鎖定圖示位置"
L["Vertical"] = "垂直圖示"
L["Vertical offset"] = "垂直位置"
L["Vertical offset from the center of the screen."] = "距離畫面正中央的垂直方向移動距離。"
L["Visibilité"] = "顯示"

L["Ovale"] = "輸出助手"
L["SpellFlash"] = "閃爍"
L["Actions"] = "動作"
L["Advanced"] = "進階"
L["Profiles"] = "設定檔"
L["Remaining time font color"] = "剩餘時間文字顏色"
L["The Ovale icon frames position has been reset."] = "輸出助手的圖示位置已經重置。"

end
